### ISSUE TITLE
Error: Invalid request, no clientRequestId. 

### ISSUE THREAD

**Issue by hung1998hy** [RodrigoBertotti/Askless#8]
Hi RodrigoBertotti
I received the error 'Invalid request, no clientRequestId,' which caused my server to stop. I tried searching for the keyword 'clientRequestId' throughout the entire codebase, but it doesn't exist. Could you please help explain this issue?

Error: Invalid request, no clientRequestId
    at OnMessage.<anonymous> (D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:89:19)
    at step (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:33:23)
    at Object.next (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:14:53)
    at D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:4:12)
    at WebSocket.OnMessage.onMessage (D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:72:52)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at Receiver.receiverOnMessage (D:\vlanceApp\server\node_modules\ws\lib\websocket.js:1220:20)

**Comment by hung1998hy** [comment]
I searched for D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:89:19, but it doesn't exist.

**Comment by hung1998hy** [comment]
> Hi RodrigoBertotti I received the error 'Invalid request, no clientRequestId,' which caused my server to stop. I tried searching for the keyword 'clientRequestId' throughout the entire codebase, but it doesn't exist. Could you please help explain this issue?
> 
> Error: Invalid request, no clientRequestId at OnMessage. (D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:89:19) at step (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:33:23) at Object.next (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:14:53) at D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:8:71 at new Promise () at __awaiter (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:4:12) at WebSocket.OnMessage.onMessage (D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:72:52) at WebSocket.emit (node:events:519:28) at WebSocket.emit (node:domain:488:12) at Receiver.receiverOnMessage (D:\vlanceApp\server\node_modules\ws\lib\websocket.js:1220:20)
