### ISSUE TITLE
Error: Invalid request, no clientRequestId. #8

### ISSUE THREAD

**Issue by hung1998hy** [RodrigoBertotti/Askless#9]
Hi RodrigoBertotti
I received the error 'Invalid request, no clientRequestId,' which caused my server to stop. I tried searching for the keyword 'clientRequestId' throughout the entire codebase, but it doesn't exist. Could you please help explain this issue?

Detailed content of error:
Error: Invalid request, no clientRequestId
at OnMessage. (D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:89:19)
at step (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:33:23)
at Object.next (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:14:53)
at D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:8:71
at new Promise ()
at __awaiter (D:\vlanceApp\server\node_modules\askless\client_middleware\ws\onMessage\onMessage.js:4:12)
at WebSocket.OnMessage.onMessage (D:\vlanceApp\server\src\client_middleware\ws\onMessage\onMessage.ts:72:52)
at WebSocket.emit (node:events:519:28)
at WebSocket.emit (node:domain:488:12)
at Receiver.receiverOnMessage (D:\vlanceApp\server\node_modules\ws\lib\websocket.js:1220:20)

**Comment by RodrigoBertotti** [comment]
Hello, could you make sure you are using the latest version on both [Node.js backend](https://www.npmjs.com/package/askless) and in the [Flutter client](https://pub.dev/packages/askless)?

**Comment by hung1998hy** [comment]
Currently I'm using NodeJS 20.15.1 and flutter 3.19.6, so I think my versions are fairly recent. The error I'm encountering only happen occasionally, but it freeze/stop my server. Can you tell me the potential of where is the error is coming from and why ?
thank you in advance

**Comment by RodrigoBertotti** [comment]
Sorry, I mean, could you please check the `pubspec.yaml` file on Flutter and check if `askless` is on the [latest version](https://pub.dev/packages/askless)? If not, please update and run `flutter pub get`

Also please check the `package.json` file in the backend is also using the [latest version](https://www.npmjs.com/package/askless) for the askless package, if not, please update and run `npm install`

**Comment by hung1998hy** [comment]
I have used the latest version of Askless for both the Node.js server and Flutter, but I still occasionally encounter this error. I think I need to monitor it for a bit longer.
